### ISSUE TITLE
Will not delete commands

### ISSUE THREAD

**Issue by rsteck** [Salandora/octoprint-customControl#14] opened 2018-02-15 23:45 UTC
After creating a command button, the plugin will not delete it.  Attempts to delete remove the template but do not save after clicking the "save" button.  Uninstalling does not remove commands.  Re-installing recognizes the previous command that was supposed to have been deleted.  

Seems like a commit problem upon deletion, but I do not have skill to dig into the code.

Otherwise extremely useful especially when working with a CNC machine for position setting.

**Comment by Salandora** [comment] 2018-02-18 10:44
Hi can you edit your button and post a screenshot? I have a feeling this could be because of a missing parameter.
Might be that you need to fix this through the console directly in octoprints config.yaml...

**Comment by rsteck** [comment] 2018-02-20 07:56
Thanks for the response.  I’m afraid that there’s nothing to show in a screenshot.  I invoke the custom  control editor, right click on the button previously defined, and select delete.  After confirming, I click Save and find that the button has not been deleted.  I can do this multiple times with the same result.

I uninstalled CCE and found that it did not eliminate the button. Reinstalling did not affect it.  I finally edited the .yaml file and removed the control, which did finally eliminate it from the system.  Defining subsequent controls was fine.

I don’t think I have any further evidence of the problem.  I could try to run the delete and see if there’s any difference in the .yaml file, but it appears to me that changes to it are not being committed during the delete function.

Great tool for setting origin on my MPCNC.

Thanks,
Randy

**Comment by electr0sheep** [comment] 2018-02-25 01:39
I can confirm this. Essentially what happens is, if you delete all the custom controls on_settings_save isn't called, and so the settings aren't getting saved. I have looked into this issue, and I am unable to determine why this occurs

https://github.com/Salandora/octoprint-customControl/blob/b684644bbe695e6253e41a2802bbc5dcb2a15f90/octoprint_customControl/__init__.py#L31-L33

**Comment by Salandora** [comment] 2018-03-04 00:43
Interesting.. will take a look at this.
12b6368 sadly is not a solution I would accept, because the customControls.controls should be an array.
But you changed it to an empty string, this can lead to other problems.
But nonetheless thank you for analyzing the problem and pointing me to the buggy code section :-)

**Comment by AvanOsch** [comment] 2018-06-17 13:38
This is still an issue.

**Comment by churusaa** [comment] 2018-06-22 22:04
Looks like changes are not committed to the Master branch. To get the fix, you will need to load up the version in Devel, which may or may not be recommended, and I would rather defer to Salandora on the question of whether or not installing from the Devel branch in its current state is safe to do.

**Closed** 2020-05-03 22:42 UTC
